pipeline {
    agent any

    tools {
        maven "Maven"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('employee-management-api/employee-management-api') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('employee-management-api/employee-management-api') {
                    withSonarQubeEnv('SonarQube') {
                        bat 'mvn sonar:sonar -DskipTests'
                    }
                }
            }
        }

        stage('Checkov Scan') {
    steps {
        bat 'checkov --version'
        dir('employee-management-api/employee-management-api/terraform') {
            catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                bat 'checkov -d . --framework terraform'
            }
        }
    }
}

        stage('OWASP Dependency Check') {
            steps {
                dir('employee-management-api/employee-management-api') {

                    withCredentials([
                        string(credentialsId: 'nvd-api-key', variable: 'NVD_API_KEY')
                    ]) {

                        dependencyCheck(
                            odcInstallation: 'DependencyCheck',
                            additionalArguments: "--scan . --format XML --format HTML --nvdApiKey ${NVD_API_KEY}"
                        )

                    }

                    dependencyCheckPublisher(
                        pattern: '**/dependency-check-report.xml'
                    )
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('employee-management-api/employee-management-api') {
                    bat 'docker build -t employee-management-api:latest .'
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                dir('employee-management-api/employee-management-api') {
                    bat 'trivy image --timeout 30m --format table -o trivy-report.txt employee-management-api:latest'
                }
            }
        }
        stage('OPA Policy Check') {
    steps {

        dir('employee-management-api/employee-management-api') {
        bat '''
        cd policy
        C:\\OPA\\opa.exe eval -i input.json -d policy.rego "data.devsecops.deny"
        '''
    }
}
    }
    stage('Fetch AWS Secret') {
    steps {
        withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-creds'
        ]]) {

            dir('employee-management-api/employee-management-api') {

                bat '''
                aws secretsmanager get-secret-value ^
                  --region ap-south-1 ^
                  --secret-id employee-management/db-password ^
                  --query SecretString ^
                  --output text > dbpassword.txt
                '''

            }
        }
    }
}

        stage('Docker Run') {
    steps {
        dir('employee-management-api/employee-management-api') {

            bat '''
            for /f %%i in (dbpassword.txt) do (
                docker rm -f employee-api
                docker run -d ^
                  --name employee-api ^
                  -e DB_PASSWORD=%%i ^
                  -p 8080:8080 ^
                  employee-management-api:latest
            )
            '''
        }
    }
}
        stage('OWASP ZAP DAST Scan') {
    steps {
        dir('employee-management-api/employee-management-api') {
            bat '''
            docker ps

            cd "C:\\Program Files\\ZAP\\Zed Attack Proxy"

            java -jar zap-2.17.0.jar ^
            -cmd ^
            -quickurl http://host.docker.internal:8080 ^
            -quickout "%CD%\\zap-report.html"
            '''
        }
    }
}
    }
}